version: 0.2

phases:
  install:
    commands:
      - echo "Instalando..."

  build:
    commands:
      - echo "Ejecutando script..."
      - python main.py

  post_build:
    commands:
      - echo "Subiendo archivo a S3..."
      - ls
      - aws s3 cp estados.json s3://estados-paola/estados.json

artifacts:
  files:
    - '**/*'
