version: 0.2

phases:
  install:
    commands:
      - echo "Instalando..."

  build:
    commands:
      - echo "Ejecutando script..."
      - python main.py

  post_build:
    commands:
      - echo "Running deploy script"
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
